services:
  - type: web
    name: poketwo-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TOKEN
        sync: false
      - key: SPAM_CHANNEL_ID
        sync: false
